"""Shared data model for hep-packaging-coordination.

Pure functions that build the canonical tool model from raw fetched data
and render it into two artifacts:

  - profile/README.md  (via render_readme)
  - site/src/data/tools.json  (via render_tools_json)

Both artifacts derive from the same model so they cannot silently diverge.
"""

from __future__ import annotations


# ── Model construction ─────────────────────────────────────────────────────────


def build_tool_model(
    feedstocks_data: dict,
    feedstock_outputs: dict[str, set[str]],
    pr_counts: dict[str, int | str],
) -> dict:
    """Build the canonical in-memory model from raw data.

    Args:
        feedstocks_data: the feedstocks.json mapping.  Values are either a
            list of feedstock names (flat category) or a dict of
            subcategory_name -> list of feedstock names (nested category).
        feedstock_outputs: mapping of feedstock_name -> set of output names,
            as returned by load_feedstock_outputs().
        pr_counts: mapping of feedstock_name -> open PR count (int) or "ERROR".

    Returns:
        dict with key "categories", each entry being:
          { "name": str,
            "feedstocks": list | None,   # None for nested categories
            "subcategories": list | None }  # None for flat categories
        where each feedstock entry is:
          { "name": str, "outputs": list[str], "pr_count": int | str }
    """
    categories = []
    for category_name, content in feedstocks_data.items():
        if isinstance(content, list):
            categories.append(
                {
                    "name": category_name,
                    "feedstocks": _build_feedstock_entries(
                        content, feedstock_outputs, pr_counts
                    ),
                    "subcategories": None,
                }
            )
        elif isinstance(content, dict):
            subcategories = []
            for sub_name, feedstock_list in content.items():
                subcategories.append(
                    {
                        "name": sub_name,
                        "feedstocks": _build_feedstock_entries(
                            feedstock_list, feedstock_outputs, pr_counts
                        ),
                    }
                )
            categories.append(
                {
                    "name": category_name,
                    "feedstocks": None,
                    "subcategories": subcategories,
                }
            )
    return {"categories": categories}


def _build_feedstock_entries(
    feedstock_names: list[str],
    feedstock_outputs: dict[str, set[str]],
    pr_counts: dict[str, int | str],
) -> list[dict]:
    """Build sorted feedstock entry dicts for a single category/subcategory."""
    entries = []
    for name in sorted(feedstock_names):
        outputs = sorted(feedstock_outputs.get(name, set()))
        entries.append(
            {
                "name": name,
                "outputs": outputs,
                "pr_count": pr_counts.get(name, 0),
            }
        )
    return entries


# ── Renderers ─────────────────────────────────────────────────────────────────


def render_tools_json(model: dict) -> dict:
    """Render the model as the tools.json data structure."""
    return {
        "generated_note": "auto-generated by update_readme.py; do not edit",
        "categories": model["categories"],
    }


def render_readme(model: dict) -> str:
    """Render the model as the profile/README.md Markdown string."""
    lines: list[str] = []
    lines.append("# HEP Packaging Coordination")
    lines.append("")
    lines.append(
        "A community project working to get as many cross-platform builds of "
        "HEP tools on conda-forge as possible."
    )
    lines.append("")
    lines.append("## Tools distributed on conda-forge")
    lines.append("")

    for category in model["categories"]:
        if category["feedstocks"] is not None:
            # Flat category — emit a single ### section.
            lines.extend(_render_section(category["name"], category["feedstocks"]))
        else:
            # Nested category — flatten: emit each subcategory as its own ### section,
            # silently skipping the parent key name (mirrors existing update_readme.py
            # behaviour where "Experiment specific" is never emitted as a heading).
            for sub in category["subcategories"]:
                lines.extend(_render_section(sub["name"], sub["feedstocks"]))

    lines.append("## Adding new tools")
    lines.append("")
    lines.append("Contributions of new HEP tools are very welcome!")
    lines.append("")
    lines.append("To get a new tool listed:")
    lines.append("1. Package and distribute your tool on conda-forge.")
    lines.append(
        '2. Open up an [Issue](https://github.com/hep-packaging-coordination/.github/issues)'
        ' with title "Add `<tool name>` to HEP Packaging Coordination"'
        " with a link to the tool's conda-forge feedstock."
    )
    lines.append("")
    return "\n".join(lines)


def _render_section(section_title: str, feedstocks: list[dict]) -> list[str]:
    """Return Markdown lines for one ### section table."""
    lines: list[str] = []
    lines.append(f"### {section_title}")
    lines.append("")
    lines.append(
        "| Name | Feedstock | Output | Downloads | Version | Platforms | Open PRs |"
    )
    lines.append("| ---| --- | --- | --- | --- | --- | --- |")
    for entry in feedstocks:
        lines.extend(_render_feedstock_rows(entry))
    lines.append("")
    return lines


def _render_feedstock_rows(entry: dict) -> list[str]:
    """Return one or more table rows for a single feedstock entry."""
    feedstock_name = entry["name"]
    outputs = entry["outputs"]
    pr_count = entry["pr_count"]

    feedstock_url = f"https://github.com/conda-forge/{feedstock_name}-feedstock"
    pr_page_url = f"{feedstock_url}/pulls"
    pr_count_link = "" if pr_count == 0 else f"[{pr_count}]({pr_page_url})"

    rows: list[str] = []
    for i, output in enumerate(outputs):
        anaconda_url = f"https://anaconda.org/conda-forge/{output}"
        # shields.io badge labels escape hyphens as '--'
        label = output.replace("-", "--")

        if i == 0:
            feedstock_badge = (
                f"[![Conda Recipe](https://img.shields.io/badge/feedstock-{label}-green.svg)]"
                f"({feedstock_url})"
            )
        else:
            feedstock_badge = ""

        recipe_badge = (
            f"[![Conda Recipe](https://img.shields.io/badge/recipe-{label}-green.svg)]"
            f"({feedstock_url})"
        )
        downloads_badge = (
            f"[![Conda Downloads](https://img.shields.io/conda/dn/conda-forge/{output}.svg)]"
            f"({anaconda_url})"
        )
        version_badge = (
            f"[![Conda Version](https://img.shields.io/conda/vn/conda-forge/{output}.svg)]"
            f"({anaconda_url})"
        )
        platforms_badge = (
            f"[![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/{output}.svg)]"
            f"({anaconda_url})"
        )

        rows.append(
            f"| {feedstock_name} | {feedstock_badge} | {recipe_badge} | "
            f"{downloads_badge} | {version_badge} | {platforms_badge} | {pr_count_link} |"
        )

    # Feedstock with no known outputs: emit one row with blanks for badge columns.
    if not outputs:
        rows.append(
            f"| {feedstock_name} |  |  |  |  |  | {pr_count_link} |"
        )

    return rows
